import { DEFAULT_TRACE_PRESET, isTracePresetId, TRACE_PRESETS } from './presets';
import type { TracePreset, TracePresetId } from './presets';

export type { TracePreset, TracePresetId };
export { DEFAULT_TRACE_PRESET, TRACE_PRESETS, isTracePresetId };

export interface TraceResult {
  /** A complete `<svg>` document. */
  svg: string;
  /** Intrinsic size of the traced document, in the source image's pixels. */
  width: number;
  height: number;
  /** How the result came out, so the UI can describe it instead of guessing. */
  stats: {
    paths: number;
    colors: number;
    /** True when the result came back with a single colour — usually a mistake. */
    flat: boolean;
  };
}

/**
 * Raster → editable SVG.
 *
 * **This lives in the CLI package on purpose.** It was first written in
 * `@iconcore/renderer`, which broke the web build: the tracer's `browser` field
 * points at a WASM package that npm refuses to install (`cpu: ["wasm32"]`), and
 * Vite follows that field while bundling the app. The renderer is imported by
 * the web app, so a Node-only WASI dependency does not belong there — which is
 * the same rule `ADR-017` already states for Chromium ("nunca em
 * `packages/iconcore-renderer`"). The CLI is Node-only and already carries
 * `@types/node`.
 *
 * The tracer is loaded with a dynamic `import()` so that even here it is not in
 * the startup path: nothing pays for it until something is traced.
 *
 * A plain `Uint8Array` is passed rather than a `Buffer`, and that is measured,
 * not stylistic: both produce byte-identical output, and `Buffer` only exists
 * in Node.
 *
 * **Where this runs today: Node only.** The browser path was built and
 * attempted and does not work — the wasm is 11 MB, npm will not install it, and
 * it fails to instantiate even in a Web Worker. The full measurement is in the
 * IC50 task; the summary is that a browser-facing tracer needs a different
 * library, not a different configuration of this one.
 */
export const traceRaster = async (
  bytes: Uint8Array,
  options: { preset?: TracePresetId } = {}
): Promise<TraceResult> => {  const preset = resolvePreset(options.preset);
  const { vectorize } = await import('@neplex/vectorizer');

  const raw = await vectorize(bytes as never, preset.config as never);
  const svg = stripXmlProlog(raw);

  const size = readIntrinsicSize(svg);
  const paths = (svg.match(/<path/g) ?? []).length;
  const colors = new Set((svg.match(/#[0-9a-f]{6}/gi) ?? []).map((c) => c.toLowerCase())).size;

  return {
    svg,
    width: size.width,
    height: size.height,
    stats: { paths, colors, flat: colors <= 1 }
  };
};

const resolvePreset = (id: TracePresetId | undefined): TracePreset => {
  if (id === undefined) return TRACE_PRESETS[DEFAULT_TRACE_PRESET];
  if (!isTracePresetId(id)) {
    throw new Error(`Unknown trace preset: ${id}`);
  }
  return TRACE_PRESETS[id];
};

/**
 * Leave the document starting at `<svg`, exactly.
 *
 * The tracer emits `<?xml version="1.0"?>` and a `<!-- Generated by … -->`
 * comment ahead of the root element. The prolog is actively harmful when the
 * result is inlined — an XML declaration has no meaning in HTML and would
 * render as visible text. Both are dropped here, once, rather than at each
 * site that renders the result, so the contract is a single checkable rule.
 */
const stripXmlProlog = (svg: string): string =>
  svg.replace(/^\s*(?:<\?xml[^>]*\?>\s*|<!--[\s\S]*?-->\s*)+/, '');

/**
 * Read `width`/`height` off the traced document.
 *
 * Measured: the tracer emits both attributes, but reading them is cheaper than
 * trusting that, and `parseSvgIntrinsicSize` already exists for exactly this.
 * Anything unreadable falls back to the source size rather than a square guess.
 */
const readIntrinsicSize = (svg: string, fallback = 512): { width: number; height: number } => {
  const width = /width="(\d+(?:\.\d+)?)"/.exec(svg);
  const height = /height="(\d+(?:\.\d+)?)"/.exec(svg);
  const w = width ? Number(width[1]) : NaN;
  const h = height ? Number(height[1]) : NaN;
  if (Number.isFinite(w) && Number.isFinite(h) && w > 0 && h > 0) {
    return { width: w, height: h };
  }
  return { width: fallback, height: fallback };
};

/** Base64 payload (what a layer stores) → bytes the tracer can read. */
export const base64ToBytes = (data: string): Uint8Array => {
  const binary = atob(data);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
};
