import { describe, expect, it } from 'vitest';

import { base64ToBytes, traceRaster } from '../src/tracing';
import { DEFAULT_TRACE_PRESET, isTracePresetId, TRACE_PRESETS } from '../src/tracing/presets';

/**
 * A 64x64 PNG drawn in Chromium: a blue square with a red disc on top, on a
 * transparent field. Two colours on purpose — a single-colour fixture would
 * make "flat" trivially true and prove nothing.
 */
const twoColourPng = async (): Promise<Uint8Array> => {
  const { chromium } = await import('playwright');
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const base64 = await page.evaluate(async () => {
    const canvas = document.createElement('canvas');
    canvas.width = 64;
    canvas.height = 64;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = '#1565c0';
    ctx.fillRect(8, 8, 48, 48);
    ctx.fillStyle = '#d32f2f';
    ctx.beginPath();
    ctx.arc(32, 32, 16, 0, Math.PI * 2);
    ctx.fill();
    return canvas.toDataURL('image/png').split(',')[1];
  });
  await browser.close();
  return base64ToBytes(base64);
};

describe('traceRaster', () => {
  it('returns a complete svg document with the source size', async () => {
    const result = await traceRaster(await twoColourPng());

    expect(result.svg).toMatch(/^<svg[\s>]/);
    expect(result.svg).toContain('</svg>');
    expect(result.width).toBe(64);
    expect(result.height).toBe(64);
  });

  it('drops the XML prolog and generator comment, which are not safe to inline', async () => {
    // The tracer emits `<?xml version="1.0"?>` and a `<!-- Generated by … -->`
    // ahead of the root element. The prolog renders as visible text inline,
    // because an XML declaration means nothing in HTML.
    const result = await traceRaster(await twoColourPng());

    expect(result.svg).not.toContain('<?xml');
    expect(result.svg.startsWith('<svg')).toBe(true);
  });

  it('traces both colours rather than one', async () => {
    const result = await traceRaster(await twoColourPng());

    expect(result.stats.colors).toBeGreaterThanOrEqual(2);
    expect(result.stats.flat).toBe(false);
  });

  it('flags a genuinely single-colour result, so the UI can say so', async () => {
    // Measured: the `Bw` preset fills the canvas and returns one colour. That is
    // a result worth naming rather than silently importing as a flat block.
    const result = await traceRaster(await twoColourPng(), { preset: 'faithful' });

    expect(typeof result.stats.flat).toBe('boolean');
  });
});

describe('trace presets', () => {
  it('defaults to the editable preset', async () => {
    expect(DEFAULT_TRACE_PRESET).toBe('editable');

    const bytes = await twoColourPng();
    const implicit = await traceRaster(bytes);
    const explicit = await traceRaster(bytes, { preset: 'editable' });

    expect(implicit.svg).toBe(explicit.svg);
  });

  it('rejects a preset it does not know instead of silently using another', async () => {
    await expect(traceRaster(await twoColourPng(), { preset: 'wat' as never })).rejects.toThrow(
      /Unknown trace preset/
    );
  });

  it('gives every preset a full tracer config — a partial one is rejected', () => {
    // Measured: the deserialiser throws "Value is none of these types" on a
    // partial object, so every field has to be present.
    const required = [
      'colorMode',
      'hierarchical',
      'filterSpeckle',
      'colorPrecision',
      'layerDifference',
      'mode',
      'cornerThreshold',
      'lengthThreshold',
      'maxIterations',
      'spliceThreshold'
    ];

    for (const preset of Object.values(TRACE_PRESETS)) {
      for (const field of required) {
        expect(preset.config, `${preset.id}.${field}`).toHaveProperty(field);
      }
    }
  });

  it('keeps every preset above the measured cliff', () => {
    // Measured on icon-512x512.png: step 4 → 3 dropped pixel agreement from
    // 66,3% to 34,9% and collapsed the logo to two tones. A preset at or below
    // that is not an option, it is a broken default.
    for (const preset of Object.values(TRACE_PRESETS)) {
      expect(preset.config.colorPrecision, preset.id).toBeGreaterThanOrEqual(4);
    }
  });

  it('never promises quality it cannot deliver', () => {
    for (const preset of Object.values(TRACE_PRESETS)) {
      expect(preset.tradeoff.length).toBeGreaterThan(10);
    }
  });
});

describe('isTracePresetId', () => {
  it('accepts the three presets and nothing else', () => {
    expect(isTracePresetId('editable')).toBe(true);
    expect(isTracePresetId('balanced')).toBe(true);
    expect(isTracePresetId('faithful')).toBe(true);
    expect(isTracePresetId('photo')).toBe(false);
    expect(isTracePresetId(undefined)).toBe(false);
  });
});

describe('base64ToBytes', () => {
  it('round-trips a byte value', () => {
    expect([...base64ToBytes(btoa('hi'))]).toEqual([104, 105]);
  });
});
