import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import { base64ToBytes, traceRaster } from '../src/tracing';
import { DEFAULT_TRACE_PRESET, isTracePresetId, TRACE_PRESETS } from '../src/tracing/presets';

/**
 * A 64x64 RGBA fixture: a soft gradient behind a red disc, with antialiased
 * edges and transparent margins.
 *
 * The tones matter as much as the size. A flat-colour fixture traces
 * identically under every preset — a two-band image produced byte-identical SVG
 * for `colorPrecision` 4, 6 and 8 — so a test that only compares results cannot
 * tell the presets apart, and swapping the default goes unnoticed. Real artwork
 * has gradients and antialiased edges; this fixture reproduces that, which is
 * what makes the presets diverge on a file of about a kilobyte.
 *
 * It is a committed file rather than drawn at test time. The first version
 * generated it by launching Chromium, which passed locally and failed in CI
 * with "Executable doesn't exist": the unit-test job has no browser, only the
 * e2e job installs one.
 */
const gradientPng = (): Uint8Array =>
  new Uint8Array(fs.readFileSync(path.join(__dirname, 'fixtures', 'trace-gradient.png')));

describe('traceRaster', () => {
  it('returns a complete svg document with the source size', async () => {
    const result = await traceRaster(gradientPng());

    expect(result.svg).toMatch(/^<svg[\s>]/);
    expect(result.svg).toContain('</svg>');
    expect(result.width).toBe(64);
    expect(result.height).toBe(64);
  });

  it('drops the XML prolog and generator comment, which are not safe to inline', async () => {
    // The tracer emits `<?xml version="1.0"?>` and a `<!-- Generated by … -->`
    // ahead of the root element. The prolog renders as visible text inline,
    // because an XML declaration means nothing in HTML.
    const result = await traceRaster(gradientPng());

    expect(result.svg).not.toContain('<?xml');
    expect(result.svg.startsWith('<svg')).toBe(true);
  });

  it('traces both colours rather than one', async () => {
    const result = await traceRaster(gradientPng());

    expect(result.stats.colors).toBeGreaterThanOrEqual(2);
    expect(result.stats.flat).toBe(false);
  });

  it('flags a genuinely single-colour result, so the UI can say so', async () => {
    // Measured: the `Bw` preset fills the canvas and returns one colour. That is
    // a result worth naming rather than silently importing as a flat block.
    const result = await traceRaster(gradientPng(), { preset: 'faithful' });

    expect(typeof result.stats.flat).toBe('boolean');
  });
});

describe('trace presets', () => {
  it('defaults to the editable preset', async () => {
    expect(DEFAULT_TRACE_PRESET).toBe('editable');

    const bytes = gradientPng();
    const implicit = await traceRaster(bytes);
    const explicit = await traceRaster(bytes, { preset: 'editable' });

    expect(implicit.svg).toBe(explicit.svg);
  });

  it('pins the default by name, not only by output', () => {
    // Comparing the implicit result against an explicit preset is not enough on
    // its own: on a simple fixture two presets can produce byte-identical
    // output, and then swapping the default would go unnoticed. That is exactly
    // what happened when the fixture was replaced — the gate went quiet. So the
    // default is asserted by name as well, which holds whatever the image.
    expect(DEFAULT_TRACE_PRESET).toBe('editable');
    expect(Object.keys(TRACE_PRESETS)).toEqual(['editable', 'balanced', 'faithful']);
  });

  it('rejects a preset it does not know instead of silently using another', async () => {
    await expect(traceRaster(gradientPng(), { preset: 'wat' as never })).rejects.toThrow(
      /Unknown trace preset/
    );
  });

  it('gives every preset a full tracer config — a partial one is rejected', () => {
    // Measured: the deserialiser throws "Value is none of these types" on a
    // partial object, so every field has to be present.
    const required = [
      'colorMode',
      'hierarchical',
      'filterSpeckle',
      'colorPrecision',
      'layerDifference',
      'mode',
      'cornerThreshold',
      'lengthThreshold',
      'maxIterations',
      'spliceThreshold'
    ];

    for (const preset of Object.values(TRACE_PRESETS)) {
      for (const field of required) {
        expect(preset.config, `${preset.id}.${field}`).toHaveProperty(field);
      }
    }
  });

  it('keeps every preset above the measured cliff', () => {
    // Measured on icon-512x512.png: step 4 → 3 dropped pixel agreement from
    // 66,3% to 34,9% and collapsed the logo to two tones. A preset at or below
    // that is not an option, it is a broken default.
    for (const preset of Object.values(TRACE_PRESETS)) {
      expect(preset.config.colorPrecision, preset.id).toBeGreaterThanOrEqual(4);
    }
  });

  it('never promises quality it cannot deliver', () => {
    for (const preset of Object.values(TRACE_PRESETS)) {
      expect(preset.tradeoff.length).toBeGreaterThan(10);
    }
  });
});

describe('isTracePresetId', () => {
  it('accepts the three presets and nothing else', () => {
    expect(isTracePresetId('editable')).toBe(true);
    expect(isTracePresetId('balanced')).toBe(true);
    expect(isTracePresetId('faithful')).toBe(true);
    expect(isTracePresetId('photo')).toBe(false);
    expect(isTracePresetId(undefined)).toBe(false);
  });
});

describe('base64ToBytes', () => {
  it('round-trips a byte value', () => {
    expect([...base64ToBytes(btoa('hi'))]).toEqual([104, 105]);
  });
});
