export { composeLayers } from './composeLayers';
export { renderProject } from './renderProject';
export { renderToSvg } from './renderToSvg';
export { sanitizeSvg } from './sanitizeSvg';
export { createCanvasBackend } from './backends/canvas';
export { createNodeBackend } from './backends/node';
export { applyMask } from './masks/applyMask';
export { layerBaseRect, containSize } from './geometry';
export type { LayerRect } from './geometry';
export type { RenderBackend, RenderContext, ImageHandle, ResolvedLayer, RenderOptions } from './types';